#!/bin/bash
export MODULEPATH=/afs/pdc.kth.se/misc/pdc/support-group/modules/Modules/sys:$MODULEPATH

module add conky
export CONKYRC=$HOME/conky/conkyrc
export CONKY_SCRIPTS=$HOME/conky/scripts

# Start conky and background ssh-processes
$CONKY_SCRIPTS/launch_conky &

# Python script watching for logout to kill the ssh processes
$CONKY_SCRIPTS/execute_on_logout &
