#!/bin/bash
export MODULEPATH=/afs/pdc.kth.se/misc/pdc/support-group/modules/Modules/sys:$MODULEPATH

module add conky

source $HOME/conky/settings

# Start conky and background ssh-processes
$CONKY_SCRIPTS/launch_conky &

# Python script watching for logout to kill the ssh processes
$CONKY_SCRIPTS/execute_on_logout &
