#!/bin/bash

export CONKY_HOME=$HOME/conky
export CONKYRC=$CONKY_HOME/conkyrc
export MACHINES=cfs-aux-4:ellen:ferlin:lindgren:milner:povel:zorn

# Later, we do this instead of repeating stuff
# for m in ${MACHINES//:/}; do     echo "$m"; done
