#!/bin/bash
machine=$2

case $1 in
	ping)
			ping -c1 -q $machine >/dev/null && echo YES || echo NO
		;;
	load)
		$CONKY_SCRIPTS/conky_ssh $machine "cat /proc/loadavg" 2> /dev/null | awk '{print $1}'
		;;
	top)
		$CONKY_SCRIPTS/conky_ssh $machine "top -n 1 -b | head -n8 | tail -n1" | awk '{ printf("%s: %s @ %.1f% \n", $2, $12, $9) }'
		;;
esac
